experiment:
    project: "radar_flowtok_ae_bl77_vae"
    name: "radar_flowtok_ae_bl77_vae_run1"
    output_dir: "/mnt/ssd_1/yghu/Experiments/radar_flowtok_ae_bl77_vae_run1"
    max_train_examples: 10_464
    save_every: 50_000
    eval_every: 50_000
    generate_every: 5_000
    log_every: 50
    log_grad_norm_every: 1_000
    resume: True

model:
    vq_model:
        quantize_mode: vae
        token_size: 16
        # vit arch
        vit_enc_model_size: "base"
        vit_dec_model_size: "large"
        vit_enc_patch_size: 16
        vit_dec_patch_size: 16
        num_latent_tokens: 77
        in_channels: 1
        out_channels: 1
        finetune_decoder: False
        is_legacy: False

losses:
    discriminator_start: 200_000
    quantizer_weight: 1.0
    discriminator_factor: 1.0
    discriminator_weight: 0.05
    perceptual_loss: "lpips-convnext_s-1.0-0.1"
    perceptual_weight: 0.2
    reconstruction_loss: "l2"
    reconstruction_weight: 1.0
    lecam_regularization_weight: 0.001
    kl_weight: 0.0
    logvar_init: 0.0

dataset:
    params:
        filelist_path: "/mnt/ssd_1/yghu/Data/71_3m/dataset_filelist.pkl"
        filelist_split: "train"
        mode: "radar"
        use_lightning: false
        num_workers: 4
    preprocessing:
        resize_shorter_edge: 128
        crop_size: 128
        random_crop: True
        random_flip: True
        res_ratio_filtering: True

optimizer:
    name: adamw 
    params:
        learning_rate: 2e-5
        discriminator_learning_rate: 2e-5
        beta1: 0.9
        beta2: 0.999
        weight_decay: 1e-4

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 10_000
        end_lr: 1e-5

training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 8
    mixed_precision: "fp16"
    enable_tf32: True
    enable_wandb: True
    use_ema: True
    seed: 42
    max_train_steps: 650_000
    num_generated_images: 2
    max_grad_norm: 1.0
    nan_check: True
    nan_skip: True 